version: '3.4'
services:
  db:
    image: kartoza/postgis:12.1
    container_name: docker_app_postgres
    volumes:
      - ./volumes/labgis/app/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gis
      - POSTGRES_PASSWORD=gis
      - POSTGRES_DBNAME=labol
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - DEFAULT_ENCODING=UTF8
      - DEFAULT_COLLATION=es_AR.UTF-8
      - DEFAULT_CTYPE=es_AR.UTF-8
    networks:
      bridge_geo:
        ipv4_address: 172.28.1.1
    ports:
      - 5432:5432

  qgisserver:
    image: camptocamp/qgis-server:latest
    container_name: docker_app_qgis
    volumes:
      - ./projects:/etc/qgisserver
    networks:
      bridge_geo:
        ipv4_address: 172.28.1.2
    extra_hosts:
      localhost: 172.28.1.1
    ports:
      - 8380:80
    depends_on:
      - db
  
  # express:
  #   build: './express-web'
  #   command: /app/node_modules/.bin/nodemon ./src/index.js
  #   container_name: docker_app_expressweb
  #   volumes:
  #     - ./express-web:/app
  #   environment: 
  #     - NODE_ENV=development
  #   networks:
  #     bridge_geo:
  #       ipv4_address: 172.28.1.3
  #   #extra_hosts:
  #   #  localhost: 172.28.1.2
  #   ports:
  #     - 3005:3005
  #   depends_on:
  #     - qgisserver

  react-ui:
    build:
      context: ./my-app
    networks:
      bridge_geo:
        ipv4_address: 172.28.1.4
    extra_hosts:
      localhost: 172.28.1.2
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
       - ./my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules
    depends_on:
      - qgisserver

networks:
  bridge_geo:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16